# Generated by Django 2.2.14 on 2020-10-06 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedItem',
            fields=[
                ('deleted_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('publish_date', models.CharField(max_length=15)),
                ('publisher', models.CharField(max_length=100)),
                ('publisher_mobile', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('square', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=50)),
                ('policy', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('deleted_date', models.DateTimeField(auto_now_add=True)),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_deleted_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_deleted_data',
            },
        ),
    ]
