# Generated by Django 2.2.14 on 2020-10-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_deleteditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=500)),
                ('param_page', models.CharField(max_length=20)),
                ('total_page', models.IntegerField()),
                ('created_user', models.CharField(max_length=50)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_system_config',
            },
        ),
    ]
