# Generated by Django 2.2.14 on 2020-10-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_systemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCrawl',
            fields=[
                ('log_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_log_crawl',
            },
        ),
    ]
