# Generated by Django 2.2.14 on 2020-10-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_auto_20201009_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='district',
            field=models.CharField(max_length=50),
        ),
    ]
